# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180925_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_file',
        ),
    ]
