# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20180903_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_category',
        ),
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentCategory'),
        ),
    ]
