# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180921_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfile',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
        ),
    ]
