# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20180907_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_icon',
            field=models.CharField(blank=True, default='fa fa-file-pdf-o', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_icon',
            field=models.CharField(blank=True, default='fa fa-file-pdf-o', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicdocument',
            name='document_icon',
            field=models.CharField(blank=True, default='fa fa-file-pdf-o', max_length=100, null=True),
        ),
    ]
