# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20180917_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_color',
            field=models.CharField(blank=True, default='#fff', max_length=200, null=True),
        ),
    ]
