# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_application_short_decription'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('contacts', models.CharField(blank=True, max_length=256, null=True)),
                ('directors', models.CharField(blank=True, max_length=256, null=True)),
                ('goods_and_services', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('goods_and_services', 'Goods and Services'), ('consultancy', 'Professional Services (consultancy)'), ('work', 'Work')], default='goods_and_services', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Service Providers',
            },
        ),
    ]
