# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_qualifiedcompanies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_description', models.CharField(default='Finance Trust Bank Image', max_length=256)),
                ('image', models.FileField(blank=True, upload_to='profile_image')),
            ],
            options={
                'verbose_name_plural': 'Image Gallery',
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='Misc', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Image Tags',
            },
        ),
    ]
