# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_imagegallery_imagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='image_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.ImageTag'),
        ),
    ]
