# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
