# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180905_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_video',
        ),
    ]
