# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_auto_20180924_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchNewsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='branch_news_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_news_file', to='website.BranchNews')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Branch News Files',
            },
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='news_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_file', to='website.News')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News Files',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
