# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_access_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telephone',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
