# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_auto_20180907_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('news_image', models.FileField(blank=True, null=True, upload_to='news_image/')),
                ('news_video', models.FileField(blank=True, null=True, upload_to='news_video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_news_entries', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_news_entry_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Happening At Branches',
            },
        ),
    ]
