# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_branchnews_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.FileField(blank=True, null=True, upload_to='event_image/'),
        ),
    ]
