# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180910_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign',
            new_name='Annoucement',
        ),
        migrations.AlterModelOptions(
            name='annoucement',
            options={'verbose_name_plural': 'Announcements'},
        ),
    ]
