# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
