# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20180924_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchnews',
            name='news_image',
        ),
        migrations.RemoveField(
            model_name='branchnews',
            name='news_video',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_video',
        ),
    ]
