# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20180927_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchnews',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='branchnews',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='branchnews',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='branchnewsfile',
            name='file_post',
        ),
        migrations.RemoveField(
            model_name='branchnewsfile',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='eventfile',
            name='file_post',
        ),
        migrations.RemoveField(
            model_name='eventfile',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='imageadvert',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='newsfile',
            name='file_post',
        ),
        migrations.RemoveField(
            model_name='newsfile',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='BranchNews',
        ),
        migrations.DeleteModel(
            name='BranchNewsFile',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventFile',
        ),
        migrations.DeleteModel(
            name='ImageAdvert',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsFile',
        ),
    ]
