# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_file', models.FileField(blank=True, null=True, upload_to='blog_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Files',
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_video',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_files/'),
        ),
        migrations.AddField(
            model_name='blogfile',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
        ),
    ]
