# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_publicdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicdocument',
            name='document_description',
        ),
    ]
