# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20180917_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_icon',
            field=models.CharField(blank=True, default='fa fa-gears', max_length=100, null=True),
        ),
    ]
