# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_birthday',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
