# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(blank=True, max_length=255, null=True)),
                ('advert_message', models.TextField(blank=True, null=True)),
                ('run_from', models.DateTimeField(blank=True, null=True)),
                ('run_to', models.DateTimeField(blank=True, null=True)),
                ('advert_image', models.FileField(blank=True, null=True, upload_to='advert_image/')),
                ('advert_video', models.FileField(blank=True, null=True, upload_to='advert_video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advert_entries', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adevert_entry_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Campaingn / Adverts',
            },
        ),
        migrations.RemoveField(
            model_name='advert',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='last_modified_by',
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
