# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180919_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annoucement',
            old_name='advert_image',
            new_name='annoucement_image',
        ),
        migrations.RenameField(
            model_name='annoucement',
            old_name='advert_message',
            new_name='annoucement_message',
        ),
        migrations.RenameField(
            model_name='annoucement',
            old_name='advert_title',
            new_name='annoucement_title',
        ),
        migrations.RenameField(
            model_name='annoucement',
            old_name='advert_video',
            new_name='annoucement_video',
        ),
    ]
