# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180919_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
