# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20180925_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='file_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='website.Event'),
        ),
    ]
