# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_publicdocument_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ManyToManyField(to='documents.DocumentCategory'),
        ),
    ]
