# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_application_application_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='short_decription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
